server.modules = ( "mod_access", "mod_alias", "mod_cgi", "mod_redirect", "mod_auth", "mod_authn_file" )

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html",
    ".txt"  => "text/plain",
    ".css"  => "text/css",
    ".js"   => "application/javascript"
)

cgi.assign = (
    ".sh" => "/bin/sh"
)

alias.url += (
    "/cgi-bin/" => "/www/cgi-bin/"
)

static-file.exclude-extensions = ( ".sh" )

server.document-root = "/www"
server.bind = "192.168.60.1"
server.port = 80

$SERVER["socket"] == "192.168.60.2:80" {
    server.document-root = "/www"
    auth.backend = "plain"
    auth.backend.plain.userfile = "/etc/lighttpd/admin.user"
    auth.require = (
        "/" => (
            "method"  => "basic",
            "realm"   => "AESD Gateway Admin",
            "require" => "valid-user"
        )
    )
    url.redirect = (
        "^/$" => "/admin/index.html"
    )
}

$SERVER["socket"] == "192.168.1.2:80" {
    url.redirect = (
        "^/(.*)$" => "http://192.168.60.2/admin/index.html"
    )
}
