#!/bin/sh

case "$1" in
    start)
        modprobe brcmfmac
        sleep 2

        ip addr flush dev eth0 2>/dev/null
        ip addr add 192.168.1.2/24 dev eth0
        ip link set eth0 up
        ip route del default 2>/dev/null
        ip route add default via 192.168.1.1

        ip addr flush dev wlan0 2>/dev/null
        ip addr add 192.168.60.1/24 dev wlan0
        ip link set wlan0 up

        echo 1 > /proc/sys/net/ipv4/ip_forward

        killall hostapd 2>/dev/null
        killall dnsmasq 2>/dev/null
        killall lighttpd 2>/dev/null

        hostapd -B /etc/hostapd.conf
        dnsmasq --conf-file=/etc/dnsmasq.conf
        lighttpd -f /etc/lighttpd/lighttpd.conf

	: > /tmp/authorized_clients

        iptables -F
        iptables -t nat -F
        iptables -P FORWARD DROP

        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

        iptables -A INPUT -i wlan0 -p udp --dport 67:68 -j ACCEPT
        iptables -A INPUT -i wlan0 -p udp --dport 53 -j ACCEPT
        iptables -A INPUT -i wlan0 -p tcp --dport 53 -j ACCEPT
        iptables -A INPUT -i wlan0 -p tcp --dport 80 -j ACCEPT

        iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j DNAT --to-destination 192.168.60.1:80
        ;;
    stop)
        killall hostapd 2>/dev/null
        killall dnsmasq 2>/dev/null
        killall lighttpd 2>/dev/null
        iptables -F
        iptables -t nat -F
        echo 0 > /proc/sys/net/ipv4/ip_forward
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
